title: Mary Githumbi
description: This is the where I discuss my Data Science journey and test my thoughts.
show_downloads: false

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "" # change this to the base hostname & protocol for your site

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: Mary Githumbi
# image: /thumbnail-jumbo.png
twitter:
  username: cera254
github:
  owner_name: marygithumbi
  owner_url: https://github.com/marygithumbi/

plugins:
  - jekyll-target-blank

target-blank:
  rel: nofollow

header_page_refs: ["about"]
